<script>
	const serviceName = "Veracy.app";
	const operatorName = "Attila Csermely";
	const lastUpdated = "2025-02-02";
	const contactEmail = "csermely.a.dev@gmail.com";
</script>

<div class="max-w-3xl px-4 py-8 text-primary overflow-auto w-full">
	<h1 class="text-5xl font-bold mb-8">Privacy Policy</h1>
	<p class="text-sm text-secondary-foreground mb-8">
		Last Updated: {lastUpdated}
	</p>

	<!-- Introduction -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">1. Introduction</h2>
		<p class="mb-4">
			This Privacy Policy explains how {serviceName} (“we,” “our,” or “the
			service”), operated by {operatorName}, collects, uses, and protects
			your data when you use our service to share and monetize content. By
			using the service, you agree to this policy.
		</p>
	</section>

	<!-- Information We Collect -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">2. Information We Collect</h2>
		<p class="mb-4">We collect only the following data:</p>
		<ul class="list-disc pl-6 space-y-3">
			<li>
				<strong>RSA Public Keys:</strong> Generated by you or our platform
				for account authentication
			</li>
			<li>
				<strong>Uploaded Images:</strong> Stored to enable public sharing
				or paid access via crypto payments
			</li>
			<li>
				<strong>Voluntary Feedback:</strong> Optional comments or suggestions
				you submit
			</li>
			<li>
				<strong>Blockchain Metadata:</strong> Metadata stored permanently
				on Arweave
			</li>
		</ul>
	</section>

	<!-- How We Use Your Data -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">3. How We Use Your Data</h2>
		<ul class="list-disc pl-6 space-y-3">
			<li>
				<strong>Public Keys:</strong> Account authentication and security
			</li>
			<li>
				<strong>Images:</strong> Service delivery and content sharing
			</li>
			<li>
				<strong>Feedback:</strong> Service improvements (anonymized)
			</li>
		</ul>
	</section>

	<!-- Data Storage & Security -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">4. Data Storage & Security</h2>
		<div class="space-y-4">
			<div>
				<h3 class="font-semibold mb-2">Storage:</h3>
				<ul class="list-disc pl-6 space-y-2">
					<li>
						Images stored in EU-based database (not encrypted at
						rest)
					</li>
					<li>Public keys stored with images, deleted on removal</li>
					<li>Blockchain metadata permanently stored on Arweave</li>
				</ul>
			</div>
			<div>
				<h3 class="font-semibold">Retention:</h3>
				<p>
					All non-blockchain data deleted immediately upon account
					deletion
				</p>
			</div>
		</div>
	</section>

	<!-- Data Sharing -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">5. Data Sharing</h2>
		<ul class="list-disc pl-6 space-y-3">
			<li>Public images accessible to anyone</li>
			<li>Paid content requires Arweave payment verification</li>
			<li>Third parties: Arweave only (blockchain metadata)</li>
		</ul>
	</section>

	<!-- GDPR Rights -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">
			6. Your Rights (GDPR Compliance)
		</h2>
		<div class="space-y-4">
			<ul class="list-disc pl-6 space-y-2">
				<li>Right to delete data</li>
				<li>Right to data export</li>
				<li>Blockchain data immutability</li>
			</ul>

			<div class="bg-secondary p-4 rounded-lg">
				<h3 class="font-semibold mb-2">Blockchain & GDPR Compliance</h3>
				<ul class="list-disc pl-6 space-y-2">
					<li>Blockchain metadata is non-personal/anonymized</li>
					<li>
						Technical impossibility of blockchain data modification
					</li>
					<li>GDPR rights exclusion for blockchain data</li>
				</ul>
			</div>
		</div>
	</section>

	<!-- User Responsibilities -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">7. User Responsibilities</h2>
		<ul class="list-disc pl-6 space-y-3">
			<li>Private key management</li>
			<li>Content restrictions and age ratings (12+, 16+, 18+)</li>
			<li>Compliance with terms</li>
		</ul>
	</section>

	<!-- Children’s Privacy -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">8. Children’s Privacy</h2>
		<p>Not intended for users under 13 years old</p>
	</section>

	<!-- International Transfers -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">
			9. International Data Transfers
		</h2>
		<p>Data stored and processed exclusively in the EU</p>
	</section>

	<!-- Policy Updates -->
	<section class="mb-8">
		<h2 class="text-2xl font-semibold mb-4">10. Policy Updates</h2>
		<p>Changes notified via in-app alerts</p>
	</section>

	<!-- Contact -->
	<section class="mt-8 pt-6 border-t border-secondary">
		<h2 class="text-2xl font-semibold mb-4">Contact</h2>
		<p class="text-blue-600 hover:underline">
			<a href="mailto:{contactEmail}">{contactEmail}</a>
		</p>
	</section>
</div>
